trigger:
  paths:
    include:
      - 'src/Stenn.CommunicationTools.Contracts'
  branches:
    include:
      - refs/heads/feature/*
      - env/clientsrc

pr: none

resources:
  repositories:
    - repository:  templates
      type: github
      name: StennGroup/stenn.pipeline-lib
      ref: refs/heads/master
      endpoint: StennGroup

extends:
  template: extendable/nuget-deploy.yaml@templates
  parameters:
    Directories:
    - dir:
      Directory: '$(Build.SourcesDirectory)/src/Stenn.CommunicationTools.Contracts'
      PackageName: 'Stenn.CommunicationTools.Contracts'
      ProjectFile: 'Stenn.CommunicationTools.Contracts.csproj'
