trigger:
  paths:
    include:
      - 'Source/StrongGrid'
  branches:
    include:
      - refs/heads/feature/*
      - refs/heads/main

pr: none

resources:
  repositories:
    - repository:  templates
      type: github
      name: StennGroup/stenn.pipeline-lib
      ref: refs/heads/master
      endpoint: StennGroup

extends:
  template: extendable/nuget-deploy.yaml@templates
  parameters:
    Directories:
    - dir:
      Directory: '$(Build.SourcesDirectory)/Source/StrongGrid'
      PackageName: 'Stenn.StrongGrid'
      ProjectFile: 'StrongGrid.csproj'
